const lessonData = {};

lessonData["01_September11.mp3"] = [{
    text: "1. Die Anschläge vom 11. September. Die Anschläge vom 11. September ereigneten sich 2001 in den Vereinigten Staaten. Dieser Tag wird „9/11“ genannt. Es war der größte Terroranschlag der Geschichte. Die Gruppe al-Qaida entführte vier Flugzeuge. Sie übernahmen mit Gewalt die Kontrolle über die Maschinen. Zwei Flugzeuge steuerten sie in die Twin Towers in New York City. Die Türme waren sehr hohe Bürogebäude. Das Feuer nach dem Aufprall ließ die Gebäude einstürzen. Ein weiteres Flugzeug traf das Pentagon, das militärische Hauptquartier. Das vierte Flugzeug stürzte auf einem Feld ab, weil die Passagiere gegen die Terroristen kämpften. Fast 3.000 Menschen starben an diesem Tag. Es war ein sehr trauriger Tag für die ganze Welt. Danach wurde das Reisen mit dem Flugzeug viel schwieriger. Die Sicherheitskontrollen an Flughäfen wurden extrem streng. Die USA begannen einen Krieg gegen Terrorgruppen in anderen Ländern. Dieses Ereignis veränderte die Welt für immer.",
    dict: { "anschläge":"saldırılar", "ereigneten":"meydana geldi", "vereinigten":"birleşik", "staaten":"devletler", "genannt":"adlandırıldı", "größte":"en büyük", "geschichte":"tarih", "entführte":"kaçırdı", "flugzeuge":"uçaklar", "übernahmen":"devraldılar", "gewalt":"şiddet", "kontrolle":"kontrol", "maschinen":"makineler", "steuerten":"yönettiler", "türme":"kuleler", "bürogebäude":"ofis binaları", "feuer":"ateş", "aufprall":"çarpma", "einstürzen":"çökmek", "weites":"diğer", "traf":"çarptı", "militärische":"askeri", "hauptquartier":"karargah", "stürzte":"düştü", "feld":"tarla/alan", "passagiere":"yolcular", "kämpften":"savaştılar", "starben":"öldüler", "trauriger":"üzücü", "ganze":"tüm", "reisen":"seyahat etmek", "schwieriger":"daha zor", "sicherheitskontrollen":"güvenlik kontrolleri", "flughäfen":"havaalanları", "streng":"sert/katı", "begannen":"başladılar", "krieg":"savaş", "ereignis":"olay", "veränderte":"değiştirdi" },
    questions: [ {q:"Ereigneten sich die Anschläge im Jahr 2001?", a_de:"Ja", a_tr:"Evet"}, {q:"Entführte al-Qaida fünf Flugzeuge?", a_de:"Nein", a_tr:"Hayır"}, {q:"Steuerten sie zwei Flugzeuge in die Twin Towers?", a_de:"Ja", a_tr:"Evet"}, {q:"Stürzten die Türme nach dem Feuer ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpften die Passagiere im vierten Flugzeug gegen die Terroristen?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde das Reisen danach einfacher?", a_de:"Nein", a_tr:"Hayır"}, {q:"Veränderte dieses Ereignis die Welt für immer?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["02_AirIndia182.mp3"] = [{
    text: "2. Der Bombenanschlag auf Air-India-Flug 182. Der Bombenanschlag auf Air-India-Flug 182 war eine furchtbare Tragödie. Er geschah 1985. Das Flugzeug flog von Kanada nach Indien und musste in London zwischenlanden. Über dem Atlantik in der Nähe Irlands explodierte eine Bombe. Die Bombe war in einem Koffer versteckt. Extremisten hatten sie dort platziert. Die Explosion zerriss das Flugzeug, und es stürzte ins Meer. Alle an Bord starben. Es waren 329 Menschen, die meisten aus Kanada. Lange Zeit war dies der schlimmste Anschlag auf ein Flugzeug. Die Polizei ermittelte jahrelang. Sie stellte fest, dass die Flughafensicherheit Fehler gemacht hatte. Die Gepäckstücke wurden nicht gründlich genug kontrolliert. Es gilt als das schlimmste Massenverbrechen in der kanadischen Geschichte.",
    dict: { "bombenanschlag":"bombalı saldırı", "furchtbare":"korkunç", "tragödie":"trajedi", "geschah":"oldu", "flugzeug":"uçak", "flog":"uçtu", "indien":"hindistan", "zwischenlanden":"aktarma yapmak", "atlantik":"atlantik", "nähe":"yakın", "explodierte":"patladı", "bombe":"bomba", "koffer":"valiz", "versteckt":"gizli", "extremisten":"aşırılıkçılar", "platziert":"yerleştirildi", "zerriss":"parçaladı", "stürzte":"düştü", "meer":"deniz", "bord":"uçak içi", "starben":"öldüler", "schlimmste":"en kötü", "ermittelte":"soruşturdu", "flughafensicherheit":"havaalanı güvenliği", "fehler":"hata", "gepäckstücke":"bagajlar", "gründlich":"detaylı", "kontrolliert":"kontrol edildi", "massenverbrechen":"toplu suç" },
    questions: [ {q:"Geschah der Anschlag im Jahr 1985?", a_de:"Ja", a_tr:"Evet"}, {q:"Flog das Flugzeug von Indien nach Kanada?", a_de:"Nein", a_tr:"Hayır"}, {q:"War die Bombe in einem Rucksack versteckt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Explodierte die Bombe über dem Atlantik?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben alle 329 Menschen an Bord?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte die Flughafensicherheit Fehler gemacht?", a_de:"Ja", a_tr:"Evet"}, {q:"Gilt es als schlimmes Massenverbrechen in Kanada?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["03_Bali.mp3"] = [{
    text: "3. Die Bali-Anschläge. Die Bali-Anschläge ereigneten sich 2002 in Indonesien. Bali ist eine wunderschöne Insel, auf der viele Menschen Urlaub machen. An einem Samstagabend griffen Terroristen das belebte Gebiet Kuta an. Viele Touristen waren dort. Die Terroristen zündeten drei Bomben. Eine Bombe steckte in einem Rucksack in einer Bar. Eine sehr große Autobombe explodierte vor einem Club. Die dritte Bombe detonierte in der Nähe eines amerikanischen Büros. Die Explosionen waren extrem stark und verursachten ein riesiges Feuer. 202 Menschen starben. Opfer kamen aus 21 verschiedenen Ländern. Viele der Toten waren junge Australier. Der Anschlag zerstörte viele Gebäude und traf die Einheimischen tief. Es dauerte lange, bis sich die Insel erholte. Man errichtete ein Denkmal für die Opfer.",
    dict: { "ereigneten":"meydana geldi", "indonesien":"endonezya", "wunderschöne":"çok güzel", "insel":"ada", "viele":"birçok", "urlaub":"tatil", "samstagabend":"cumartesi akşamı", "griffen":"saldırdılar", "belebte":"kalabalık", "gebiet":"bölge", "touristen":"turistler", "zündeten":"ateşlediler", "drei":"üç", "steckte":"duruyordu", "rucksack":"sırt çantası", "bar":"bar", "große":"büyük", "autobombe":"bombalı araç", "club":"kulüp", "detonierte":"patladı", "amerikanischen":"amerikan", "büros":"ofisler", "explosionen":"patlamalar", "stark":"güçlü", "verursachten":"sebep oldular", "riesiges":"devasa", "opfer":"kurbanlar", "verschiedenen":"farklı", "ländern":"ülkeler", "tote":"ölüler", "junge":"genç", "australier":"avustralyalılar", "zerstörte":"yok etti", "gebäude":"binalar", "traf":"etkiledi", "einheimischen":"yerliler", "tief":"derin", "erholte":"iyileşti/toparlandı", "errichtete":"inşa edildi", "denkmal":"anıt" },
    questions: [ {q:"Fanden die Anschläge auf Bali im Jahr 2002 statt?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist Bali eine hässliche Insel?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zündeten die Terroristen drei Bomben?", a_de:"Ja", a_tr:"Evet"}, {q:"Explodierte eine Autobombe vor einem Club?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben mehr als 500 Menschen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Waren viele Opfer aus Australien?", a_de:"Ja", a_tr:"Evet"}, {q:"Gibt es heute ein Denkmal für die Opfer?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["04_Beslan.mp3"] = [{
    text: "4. Die Geiselnahme in der Schule von Beslan. Die Geiselnahme in der Schule von Beslan fand 2004 in Russland statt. Sie begann am 1. September. In Russland ist das der erste Schultag – normalerweise ein freudiger Anlass für Kinder und Eltern. Doch bewaffnete Rebellen stürmten die Schule. Sie nahmen mehr als 1.100 Menschen als Geiseln, die meisten Kinder. Die Geiseln wurden in die Sporthalle gebracht. Drei Tage lang bekamen sie weder Essen noch Wasser. Es war sehr heiß und überfüllt. Die Rebellen forderten den Abzug der russischen Armee aus ihrer Region. Am dritten Tag gab es Explosionen in der Halle. Russische Soldaten stürmten die Schule, um die Geiseln zu befreien. Bei den Kämpfen starben 334 Menschen, mehr als die Hälfte davon Kinder. Es war ein herzzerreißendes Ereignis, das die Welt schockierte.",
    dict: { "geiselnahme":"rehin alma", "schule":"okul", "russland":"rusya", "begann":"başladı", "september":"eylül", "erste":"ilk", "schultag":"okul günü", "normalerweise":"normalde", "freudiger":"neşeli", "anlass":"sebep/vesile", "eltern":"ebeveynler", "bewaffnete":"silahlı", "rebellen":"isyancılar", "stürmten":"bastılar/saldırdılar", "reih":"fazla", "geiseln":"rehineler", "meisten":"çoğu", "sporthalle":"spor salonu", "gebracht":"getirildi", "drei":"üç", "tage":"günler", "bekamen":"aldılar", "weder":"ne...", "noch":"...ne de", "essen":"yemek", "wasser":"su", "heiß":"sıcak", "überfüllt":"aşırı kalabalık", "forderten":"talep ettiler", "abzug":"geri çekilme", "armee":"ordu", "region":"bölge", "soldaten":"askerler", "befreien":"kurtarmak", "kämpfen":"savaşlar", "hälfte":"yarı", "herzzerreißendes":"yürek burkan", "schockierte":"şok etti" },
    questions: [ {q:"Begann die Geiselnahme am ersten Schultag?", a_de:"Ja", a_tr:"Evet"}, {q:"Nahmen die Rebellen nur Erwachsene als Geiseln?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurden die Menschen in die Sporthalle gebracht?", a_de:"Ja", a_tr:"Evet"}, {q:"Bekamen die Geiseln viel zu essen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Dauerte die Geiselnahme drei Tage?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben mehr als 300 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Waren viele der Toten Kinder?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["05_Entebbe.mp3"] = [{
    text: "5. Die Entführung von Entebbe. Die Entführung von Entebbe geschah 1976. Eine Air-France-Maschine flog von Israel nach Frankreich. Vier Terroristen – zwei Palästinenser und zwei Deutsche – übernahmen das Flugzeug. Sie zwangen den Piloten, nach Uganda in Afrika zu fliegen. Der ugandische Präsident Idi Amin unterstützte die Terroristen. Sie hielten die jüdischen und israelischen Passagiere als Geiseln fest und ließen die anderen frei. Sie drohten, die Geiseln zu töten, wenn ihre Forderungen nicht erfüllt würden. Israel schickte ein Spezialkommando zur Rettung. Die Soldaten flogen heimlich sehr weit. Nachts landeten sie am Flughafen. In einem kurzen Gefecht befreiten sie 102 Menschen. Der Kommandoführer Yonatan Netanyahu wurde getötet. Die Operation ist berühmt, weil sie so mutig und erfolgreich war.",
    dict: { "entführung":"kaçırma", "geschah":"oldu", "maschine":"uçak", "israel":"israil", "frankreich":"fransa", "vier":"dört", "palästinenser":"filistinli", "deutsche":"alman", "übernahmen":"ele geçirdiler", "zwangen":"zorladılar", "piloten":"pilot", "uganda":"uganda", "afrika":"afrika", "präsident":"başkan", "unterstützte":"destekledi", "hielten":"tuttular", "jüdischen":"yahudi", "israelischen":"israilli", "passagiere":"yolcular", "geiseln":"rehineler", "fest":"sıkı/rehin (festhalten)", "ließen":"bıraktılar", "frei":"serbest", "drohten":"tehdit ettiler", "töten":"öldürmek", "forderungen":"talepler", "erfüllt":"yerine getirildi", "schickte":"gönderdi", "spezialkommando":"özel komando", "rettung":"kurtarma", "soldaten":"askerler", "heimlich":"gizlice", "weit":"uzak", "nachts":"geceleyin", "landeten":"indiler", "flughafen":"havaalanı", "kurzen":"kısa", "gefecht":"çatışma", "befreiten":"kurtardılar", "kommandoführer":"komando lideri", "getötet":"öldürüldü", "operation":"operasyon", "berühmt":"ünlü", "mutig":"cesur", "erfolgreich":"başarılı" },
    questions: [ {q:"Flog die Air-France-Maschine nach Amerika?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zwangen die Terroristen den Piloten, nach Uganda zu fliegen?", a_de:"Ja", a_tr:"Evet"}, {q:"Unterstützte Idi Amin die Terroristen?", a_de:"Ja", a_tr:"Evet"}, {q:"Ließen die Terroristen alle Passagiere sofort frei?", a_de:"Nein", a_tr:"Hayır"}, {q:"Schickte Israel ein Spezialkommando?", a_de:"Ja", a_tr:"Evet"}, {q:"Befreiten die Soldaten 102 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"War die Operation erfolgreich?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["06_Garissa.mp3"] = [{
    text: "6. Der Angriff auf die Garissa-Universität. Der Angriff auf die Garissa-Universität ereignete sich 2015 in Kenia. Es war früh am Morgen. Studenten schliefen oder lernten für Prüfungen. Bewaffnete einer Terrorgruppe drangen in die Uni ein. Sie töteten die Wachen am Tor. Dann gingen sie in Hörsäle und Schlafsäle. Sie suchten gezielt christliche Studenten und töteten sie. Muslimische Studenten ließen sie teilweise frei. Der Angriff dauerte etwa 15 Stunden. Die Studenten hatten große Angst. Polizei und Armee umstellten die Gebäude. Schließlich töteten die Sicherheitskräfte die vier Angreifer. Doch für viele war es zu spät. 148 Menschen starben, die meisten junge Studenten mit Zukunft. Es war ein sehr trauriger Tag für Kenia. Er zeigte, dass Schulen besseren Schutz brauchen.",
    dict: { "angriff":"saldırı", "universität":"üniversite", "kenia":"kenya", "früh":"erken", "morgen":"sabah", "studenten":"öğrenciler", "schliefen":"uyuyorlardı", "lernten":"çalışıyorlardı", "prüfungen":"sınavlar", "bewaffnete":"silahlı kişiler", "drangen":"girdiler (eindringen)", "töteten":"öldürdüler", "wachen":"bekçiler", "tor":"kapı/geçit", "hörsäle":"derslikler", "schlafsäle":"yatakhaneler", "suchten":"aradılar", "gezielt":"hedefli", "christliche":"hristiyan", "muslimische":"müslüman", "teilweise":"kısmen", "dauerte":"sürdü", "angst":"korku", "polizei":"polis", "armee":"ordu", "umstellten":"kuşattılar", "gebäude":"binalar", "schließlich":"sonunda", "sicherheitskräfte":"güvenlik güçleri", "angreifer":"saldırganlar", "spät":"geç", "starben":"öldüler", "zukunft":"gelecek", "trauriger":"üzücü", "schulen":"okullar", "besseren":"daha iyi", "schutz":"koruma", "brauchen":"ihtiyaç duymak" },
    questions: [ {q:"Ereignete sich der Angriff im Jahr 2015?", a_de:"Ja", a_tr:"Evet"}, {q:"Schliefen viele Studenten während des Angriffs?", a_de:"Ja", a_tr:"Evet"}, {q:"Töteten die Angreifer gezielt christliche Studenten?", a_de:"Ja", a_tr:"Evet"}, {q:"Dauerte der Angriff nur eine Stunde?", a_de:"Nein", a_tr:"Hayır"}, {q:"Umstellten Polizei und Armee die Uni?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben 148 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Brauchen Schulen in Kenia besseren Schutz?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["07_Mekka.mp3"] = [{
    text: "7. Die Besetzung der Großen Moschee. Die Besetzung der Großen Moschee geschah 1979 in Saudi-Arabien. Die Große Moschee in Mekka ist der heiligste Ort des Islam. Gewalt ist dort verboten. Doch eine bewaffnete Gruppe stürmte die Moschee. Ihr Anführer behauptete, ein neuer Erlöser sei gekommen. Sie verriegelten die Türen und hielten Tausende Menschen fest. Die Regierung war schockiert. Sie wollte das heilige Gebäude nicht beschädigen. Die Belagerung dauerte zwei Wochen. Die saudi-arabische Armee kämpfte hart, um die Moschee zurückzuerobern. Französische Experten halfen ihnen. Viele Menschen starben bei den Kämpfen. Die Moschee wurde beschädigt, aber später repariert. Danach wurde die saudische Regierung viel strenger bei Religion und Regeln im Land.",
    dict: { "besetzung":"işgal", "moschee":"cami", "saudi-arabien":"suudi arabistan", "heiligste":"en kutsal", "ort":"yer", "islam":"islam", "gewalt":"şiddet", "verboten":"yasak", "bewaffnete":"silahlı", "gruppe":"grup", "stürmte":"bastı/saldırdı", "anführer":"lider", "behauptete":"iddia etti", "erlöser":"kurtarıcı", "gekommen":"geldi", "verriegelten":"kilitlediler", "türen":"kapılar", "hielten":"tuttular", "tausende":"binlerce", "fest":"sıkı/rehin (festhalten)", "regierung":"hükümet", "schockiert":"şok olmuş", "heilige":"kutsal", "gebäude":"bina", "beschädigen":"zarar vermek", "belagerung":"kuşatma", "zwei":"iki", "wochen":"haftalar", "kämpfte":"savaştı", "hart":"sert", "zurückzuerobern":"geri almak", "französische":"fransız", "experten":"uzmanlar", "halfen":"yardım ettiler", "starben":"öldüler", "repariert":"tamir edildi", "strenger":"daha katı", "religion":"din", "regeln":"kurallar", "land":"ülke" },
    questions: [ {q:"Ist die Große Moschee in Mekka ein heiliger Ort?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist Gewalt in der Moschee erlaubt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Behauptete der Anführer, er sei ein Erlöser?", a_de:"Ja", a_tr:"Evet"}, {q:"Dauerte die Belagerung nur zwei Tage?", a_de:"Nein", a_tr:"Hayır"}, {q:"Halfen französische Experten der Armee?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde die Moschee bei den Kämpfen beschädigt?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde die Regierung danach strenger?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["08_Jonestown.mp3"] = [{
    text: "8. Das Massaker von Jonestown. Das Massaker von Jonestown ereignete sich 1978 in Guyana. Es betraf die Sekte Peoples Temple. Der Anführer war Jim Jones. Er überredete seine Anhänger, in den Dschungel zu ziehen, um einen perfekten Ort zu schaffen. Doch das Leben dort war hart. Jones war ein schlechter Führer. Er kontrollierte alle. Ein US-Politiker kam, um nach den Leuten zu sehen. Jones ließ ihn ermorden. Danach befahl er allen Anhängern, zu sterben. Er mischte Gift in einen Trank. Eltern gaben ihn zuerst ihren Babys, dann tranken die Erwachsenen. Insgesamt starben 918 Menschen. Es war eine furchtbare Tragödie. Sie zeigte, wie gefährlich Sektenführer werden können, wenn sie zu viel Macht über Menschen haben.",
    dict: { "massaker":"katliam", "guyana":"guyana", "betraf":"ilgilendirdi/etkiledi", "sekte":"tarikat", "anführer":"lider", "überredete":"ikna etti", "anhänger":"takipçiler", "dschungel":"orman", "ziehen":"taşınmak/gitmek", "perfekten":"mükemmel", "schaffen":"yaratmak", "hart":"zor", "schlechter":"kötü", "führer":"lider", "kontrollierte":"kontrol etti", "politiker":"politikacı", "kam":"geldi", "ermorden":"öldürmek (cinayet)", "befahl":"emretti", "sterben":"ölmek", "mischte":"karıştırdı", "gift":"zehir", "trank":"içecek", "eltern":"ebeveynler", "babys":"bebekler", "erwachsenen":"yetişkinler", "insgesamt":"toplamda", "starben":"öldüler", "furchtbare":"korkunç", "tragödie":"trajedi", "zeigte":"gösterdi", "gefährlich":"tehlikeli", "sektenführer":"tarikat lideri", "macht":"güç" },
    questions: [ {q:"Ereignete sich das Massaker in Guyana?", a_de:"Ja", a_tr:"Evet"}, {q:"War Jim Jones ein guter Führer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zogen die Menschen in den Dschungel?", a_de:"Ja", a_tr:"Evet"}, {q:"Ließ Jones einen Politiker ermorden?", a_de:"Ja", a_tr:"Evet"}, {q:"Mischte Jones Gift in einen Trank?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben weniger als 100 Menschen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Hatte Jim Jones zu viel Macht über die Menschen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["09_Lockerbie.mp3"] = [{
    text: "9. Der Lockerbie-Anschlag. Der Lockerbie-Anschlag geschah 1988. Pan-Am-Flug 103 flog nach New York. Hoch über Schottland explodierte eine Bombe an Bord. Die Bombe war in einem Radio in einem Koffer versteckt. Die Explosion zerfetzte das Flugzeug. Es stürzte auf die kleine Stadt Lockerbie. Alle 259 Menschen an Bord starben. Große Trümmerteile trafen Häuser am Boden und töteten 11 weitere Personen. Insgesamt starben 270 Menschen. Ermittler untersuchten die Trümmer lange. Sie fanden heraus, dass Männer aus Libyen den Anschlag planten. Es ist der schlimmste Terroranschlag, der je im Vereinigten Königreich stattfand. In Lockerbie gedenkt man den Opfern bis heute.",
    dict: { "anschlag":"saldırı", "geschah":"oldu", "flug":"uçuş", "flog":"uçtu", "hoch":"yüksek", "schottland":"iskoçya", "explodierte":"patladı", "bombe":"bomba", "bord":"uçak içi", "radio":"radyo", "koffer":"valiz", "versteckt":"gizli", "explosion":"patlama", "zerfetzte":"parçaladı", "flugzeug":"uçak", "stürzte":"düştü", "kleine":"küçük", "stadt":"şehir", "starben":"öldüler", "trümmerteile":"enkaz parçaları", "trafen":"çarptılar", "häuser":"evler", "boden":"zemin", "töteten":"öldürdüler", "weitere":"diğer/fazladan", "personen":"kişiler", "insgesamt":"toplamda", "ermittler":"müfettişler", "untersuchten":"incelediler", "trümmer":"enkaz", "lange":"uzun süre", "fanden":"buldular", "heraus":"dışarı (herausfinden: bulup çıkarmak)", "libyen":"libya", "planten":"planladılar", "schlimmste":"en kötü", "vereinigten":"birleşik", "königreich":"krallık", "stattfand":"gerçekleşti", "gedenkt":"anılıyor", "opfern":"kurbanlar" },
    questions: [ {q:"Geschah der Anschlag im Jahr 1988?", a_de:"Ja", a_tr:"Evet"}, {q:"Flog das Flugzeug nach New York?", a_de:"Ja", a_tr:"Evet"}, {q:"War die Bombe in einem Radio versteckt?", a_de:"Ja", a_tr:"Evet"}, {q:"Stürzte das Flugzeug ins Meer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben auch Menschen am Boden in Lockerbie?", a_de:"Ja", a_tr:"Evet"}, {q:"Plannten Männer aus Libyen den Anschlag?", a_de:"Ja", a_tr:"Evet"}, {q:"Gedenkt man den Opfern heute noch?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["10_London77.mp3"] = [{
    text: "10. Die Londoner Anschläge vom 7. Juli. Die Londoner Anschläge vom 7. Juli 2005 werden „7/7“ genannt. Es war ein hektischer Morgen in London. Die Menschen fuhren zur Arbeit. Vier Männer trugen Rucksäcke mit Bomben. Drei stiegen in U-Bahnen und zündeten ihre Bomben fast gleichzeitig. Die Züge waren in Tunneln, es war dunkel und furchterregend. Später zündete der vierte Mann seine Bombe in einem roten Doppeldeckerbus. Die Anschläge töteten 52 Menschen und verletzten Hunderte. Die Täter waren Briten mit extremistischen Ideen. Der Anschlag legte die ganze Stadt lahm. Niemand konnte reisen. Es war ein sehr beängstigender Tag für London. Er veränderte das Sicherheitsgefühl in Zügen und Bussen.",
    dict: { "londoner":"londra", "juli":"temmuz", "genannt":"adlandırıldı", "hektischer":"hareketli/telaşlı", "morgen":"sabah", "menschen":"insanlar", "fuhren":"gittiler/sürdüler", "arbeit":"iş", "vier":"dört", "männer":"adamlar", "trugen":"taşıdılar", "rucksäcke":"sırt çantaları", "bomben":"bombalar", "stiegen":"bindiler", "u-bahnen":"metrolar", "zündeten":"ateşlediler", "fast":"neredeyse", "gleichzeitig":"aynı anda", "züge":"trenler", "tunneln":"tüneller", "dunkel":"karanlık", "furchterregend":"korkutucu", "später":"sonra", "rote":"kırmızı", "doppeldeckerbus":"iki katlı otobüs", "töteten":"öldürdüler", "verletzten":"yaraladılar", "hunderte":"yüzlerce", "täter":"failler", "briten":"ingilizler", "extremistischen":"aşırılıkçı", "ideen":"fikirler", "legte":"koydu/yaptı (lahm legen: felç etmek)", "lahm":"felç", "niemand":"hiç kimse", "konnte":"yapabildi", "reisen":"seyahat etmek", "beängstigender":"korkutucu", "tag":"gün", "veränderte":"değiştirdi", "sicherheitsgefühl":"güvenlik hissi", "bussen":"otobüsler" },
    questions: [ {q:"Werden die Anschläge „7/7“ genannt?", a_de:"Ja", a_tr:"Evet"}, {q:"Fuhren die Menschen am Abend nach Hause?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zündeten drei Männer Bomben in U-Bahnen?", a_de:"Ja", a_tr:"Evet"}, {q:"Explodierte die vierte Bombe in einem Taxi?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben 52 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Waren die Täter Ausländer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Veränderte der Anschlag das Sicherheitsgefühl?", a_de:"Ja", a_tr:"Evet"} ]
}];lessonData["11_Madrid.mp3"] = [{
    text: "11. Die Zuganschläge von Madrid. Die Zuganschläge von Madrid ereigneten sich 2004 in Spanien. Es war die morgendliche Stoßzeit. Viele Menschen fuhren zur Arbeit oder Schule. Terroristen platzierten Rucksäcke mit Bomben in vier Zügen. Zehn Bomben explodierten. Es gab enorme Zerstörung. Die Züge wurden zerstört. 193 Menschen starben, fast 2.000 wurden verletzt. Es war der schlimmste Anschlag in der spanischen Geschichte. Zuerst dachte die Regierung an eine lokale Gruppe. Später stellte sich heraus, dass al-Qaida-nahe Terroristen dahintersteckten. Der Anschlag geschah drei Tage vor einer wichtigen Wahl. Die Menschen waren wütend und traurig. Millionen gingen auf die Straße, um gegen Terrorismus zu protestieren. Es war eine sehr schwere Zeit für Spanien.",
    dict: { "zuganschläge":"tren saldırıları", "spanien":"ispanya", "morgendliche":"sabah", "stoßzeit":"yoğun saat", "viele":"birçok", "schule":"okul", "platzierten":"yerleştirdiler", "rucksäcke":"sırt çantaları", "bomben":"bombalar", "vier":"dört", "zügen":"trenler", "zehn":"on", "explodierten":"patladılar", "enorme":"muazzam", "zerstörung":"yıkım", "zerstört":"yok edildi", "starben":"öldüler", "verletzt":"yaralı", "schlimmste":"en kötü", "geschichte":"tarih", "zuerst":"önce", "dachte":"düşündü", "regierung":"hükümet", "lokale":"yerel", "gruppe":"grup", "später":"sonra", "heraus":"dışarı (herausstellen: ortaya çıkmak)", "terroristen":"teröristler", "dahintersteckten":"arkasında olmak", "geschah":"oldu", "drei":"üç", "tage":"günler", "vor":"önce", "wichtigen":"önemli", "wahl":"seçim", "wütend":"kızgın", "traurig":"üzgün", "millionen":"milyonlar", "gingen":"gittiler", "straße":"cadde", "gegen":"karşı", "protestieren":"protesto etmek", "schwere":"zor/ağır", "zeit":"zaman" },
    questions: [ {q:"Fanden die Anschläge in Spanien statt?", a_de:"Ja", a_tr:"Evet"}, {q:"War es während der morgendlichen Stoßzeit?", a_de:"Ja", a_tr:"Evet"}, {q:"Explodierten zehn Bomben in den Zügen?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben nur zehn Menschen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Steckten al-Qaida-nahe Terroristen dahinter?", a_de:"Ja", a_tr:"Evet"}, {q:"Geschah der Anschlag nach einer Wahl?", a_de:"Nein", a_tr:"Hayır"}, {q:"Protestierten Millionen Menschen gegen Terrorismus?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["12_MoskauTheater.mp3"] = [{
    text: "12. Die Geiselnahme im Moskauer Theater. Die Geiselnahme im Moskauer Theater fand 2002 statt. Ein beliebtes Musical lief im Theater. Plötzlich stürmten etwa 40 bewaffnete Rebellen herein. Sie stoppten die Vorstellung und nahmen 850 Menschen als Geiseln. Die Rebellen kamen aus Tschetschenien. Sie forderten den Abzug der russischen Armee aus ihrem Land. Sie legten Sprengstoff um das Theater. Die Belagerung dauerte drei Tage. Russische Spezialeinheiten wollten die Geiseln ohne Kampf retten. Sie pumpten Gas ins Theater, um alle schlafen zu legen. Dann stürmten die Soldaten herein und töteten die Rebellen. Doch das Gas war zu stark. Es tötete 132 Geiseln, weil sie nicht atmen konnten. Es war eine Tragödie, weil der Rettungsplan so viele Tote verursachte.",
    dict: { "geiselnahme":"rehin alma", "theater":"tiyatro", "beliebtes":"popüler", "musical":"müzikal", "lief":"oynuyordu/çalışıyordu", "plötzlich":"aniden", "stürmten":"bastılar/saldırdılar", "bewaffnete":"silahlı", "rebellen":"isyancılar", "herein":"içeri", "stoppten":"durdurdular", "vorstellung":"gösteri", "reih":"fazla", "geiseln":"rehineler", "kamen":"geldiler", "tschetschenien":"çeçenistan", "forderten":"talep ettiler", "abzug":"geri çekilme", "armee":"ordu", "land":"ülke", "legten":"koydular", "sprengstoff":"patlayıcı", "belagerung":"kuşatma", "dauerte":"sürdü", "drei":"üç", "tage":"günler", "spezialeinheiten":"özel birimler", "wollten":"istediler", "ohne":"olmadan", "kampf":"savaş/çatışma", "retten":"kurtarmak", "pumpten":"pompaladılar", "gas":"gaz", "schlafen":"uyumak", "soldaten":"askerler", "töteten":"öldürdüler", "stark":"güçlü", "atmen":"nefes almak", "konnten":"bildiler", "tragödie":"trajedi", "rettungsplan":"kurtarma planı", "verursachte":"sebep oldu" },
    questions: [ {q:"Fand die Geiselnahme während eines Musicals statt?", a_de:"Ja", a_tr:"Evet"}, {q:"Nahmen die Rebellen 850 Menschen als Geiseln?", a_de:"Ja", a_tr:"Evet"}, {q:"Forderten die Rebellen Geld?", a_de:"Nein", a_tr:"Hayır"}, {q:"Dauerte die Belagerung drei Tage?", a_de:"Ja", a_tr:"Evet"}, {q:"Pumpten die Soldaten Gas ins Theater?", a_de:"Ja", a_tr:"Evet"}, {q:"War das Gas für alle Geiseln sicher?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben 132 Geiseln durch das Gas?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["13_Mumbai.mp3"] = [{
    text: "13. Die Anschläge von Mumbai. Die Anschläge von Mumbai ereigneten sich 2008 in Indien. Sie dauerten vier Tage. Zehn Terroristen kamen per Boot in die Stadt. Sie hatten Gewehre und Granaten. Sie griffen viele Orte an: Bahnhof, Krankenhaus, Café. Sie besetzten auch zwei Luxushotels, darunter das berühmte Taj Mahal Palace. Sie nahmen Menschen als Geiseln. Polizei und Armee kämpften lange gegen sie. Die ganze Welt schaute im Fernsehen zu. Die Hotels brannten. Am Ende starben 166 Menschen. Nur ein Terrorist wurde lebend gefasst und später verurteilt. Man nennt es „Indiens 9/11“, weil es so groß und schockierend war.",
    dict: { "mumbai":"mumbai", "ereigneten":"meydana geldi", "indien":"hindistan", "dauerten":"sürdüler", "vier":"dört", "tage":"günler", "zehn":"on", "kamen":"geldiler", "boot":"tekne", "stadt":"şehir", "gewehre":"tüfekler", "granaten":"bombalar/el bombaları", "griffen":"saldırdılar", "viele":"birçok", "orte":"yerler", "bahnhof":"tren istasyonu", "krankenhaus":"hastane", "besetzten":"işgal ettiler", "luxushotels":"lüks oteller", "darunter":"aralarında", "berühmte":"ünlü", "geiseln":"rehineler", "polizei":"polis", "armee":"ordu", "kämpften":"savaştılar", "lange":"uzun süre", "gegen":"karşı", "ganze":"tüm", "welt":"dünya", "schaute":"izledi", "fernsehen":"televizyon", "brannten":"yandılar", "ende":"son", "starben":"öldüler", "terrorist":"terörist", "lebend":"canlı", "gefasst":"yakalandı", "später":"sonra", "verurteilt":"mahkum edildi", "nennt":"adlandırır", "schockierend":"şok edici" },
    questions: [ {q:"Dauerten die Anschläge in Mumbai vier Tage?", a_de:"Ja", a_tr:"Evet"}, {q:"Kamen die Terroristen mit dem Flugzeug?", a_de:"Nein", a_tr:"Hayır"}, {q:"Griffen sie auch ein Krankenhaus an?", a_de:"Ja", a_tr:"Evet"}, {q:"Besetzten sie das Taj Mahal Palace Hotel?", a_de:"Ja", a_tr:"Evet"}, {q:"Schaute die Welt im Fernsehen zu?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurden alle Terroristen lebend gefasst?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben 166 Menschen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["14_Muenchen72.mp3"] = [{
    text: "14. Das Massaker bei den Olympischen Spielen in München. Das Massaker bei den Olympischen Spielen geschah 1972 in Deutschland. Die Olympischen Spiele stehen für Frieden und Sport. Doch die Terrorgruppe „Schwarzer September“ drang in das Athletendorf ein. Sie ging in die Unterkünfte der israelischen Mannschaft. Sie töteten zwei Sportler und nahmen neun als Geiseln. Sie forderten die Freilassung von Gefangenen aus Israel. Die deutsche Polizei versuchte, die Terroristen zu täuschen und die Geiseln am Flughafen zu befreien. Doch der Plan scheiterte. Es kam zu einem Schusswechsel. Die Terroristen töteten alle neun Geiseln. Auch ein Polizist starb. Die Spiele wurden für einen Tag unterbrochen. Es war sehr traurig. Danach wurde die Sicherheit bei Sportveranstaltungen viel strenger.",
    dict: { "massaker":"katliam", "olympischen":"olimpiyat", "spielen":"oyunlar", "münchen":"münih", "geschah":"oldu", "deutschland":"almanya", "stehen":"durmak/temsil etmek", "frieden":"barış", "sport":"spor", "terrorgruppe":"terör grubu", "schwarzer":"siyah", "september":"eylül", "drang":"girdi (eindringen)", "athletendorf":"sporcu köyü", "unterkünfte":"konaklama yerleri", "israelischen":"israil", "mannschaft":"takım", "töteten":"öldürdüler", "zwei":"iki", "sportler":"sporcular", "neun":"dokuz", "geiseln":"rehineler", "forderten":"talep ettiler", "freilassung":"serbest bırakma", "gefangenen":"mahkumlar", "polizei":"polis", "versuchte":"denedi", "täuschen":"kandırmak", "flughafen":"havaalanı", "befreien":"kurtarmak", "plan":"plan", "scheiterte":"başarısız oldu", "schusswechsel":"çatışma", "polizist":"polis memuru", "starb":"öldü", "unterbrochen":"ara verildi", "traurig":"üzgün", "sicherheit":"güvenlik", "sportveranstaltungen":"spor etkinlikleri", "strenger":"daha katı" },
    questions: [ {q:"Geschah das Massaker während der Olympischen Spiele 1972?", a_de:"Ja", a_tr:"Evet"}, {q:"Drang die Terrorgruppe in das Athletendorf ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Waren die Geiseln aus der israelischen Mannschaft?", a_de:"Ja", a_tr:"Evet"}, {q:"Befreite die Polizei alle Geiseln sicher?", a_de:"Nein", a_tr:"Hayır"}, {q:"Töteten die Terroristen alle neun Geiseln?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb auch ein Polizist?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde die Sicherheit danach strenger?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["15_Nairobi.mp3"] = [{
    text: "15. Der Bombenanschlag auf die Botschaft in Nairobi. Der Bombenanschlag auf die US-Botschaft in Nairobi geschah 1998. Terroristen griffen gleichzeitig die amerikanischen Botschaften in Kenia und Tansania an. Sie nutzten mit Bomben beladene Lastwagen. Die Bomben explodierten fast gleichzeitig. In Nairobi war der Schaden besonders groß. Die Botschaft wurde beschädigt, aber ein Nachbargebäude stürzte komplett ein. Darin waren Büros und eine Schule. Mehr als 200 Menschen starben, die meisten Kenianer. Tausende wurden durch Glassplitter und Trümmer verletzt. Osama bin Laden plante den Anschlag. Es war das erste Mal, dass viele von seiner Gruppe al-Qaida hörten. Er zeigte, dass Terrorismus ein globales Problem ist.",
    dict: { "bombenanschlag":"bombalı saldırı", "botschaft":"elçilik", "nairobi":"nairobi", "geschah":"oldu", "griffen":"saldırdılar", "gleichzeitig":"aynı anda", "amerikanischen":"amerikan", "kenia":"kenya", "tansania":"tanzanya", "nutzten":"kullandılar", "beladene":"yüklü", "lastwagen":"kamyonlar", "explodierten":"patladılar", "fast":"neredeyse", "schaden":"zarar", "besonders":"özellikle", "groß":"büyük", "beschädigt":"hasar gördü", "nachbargebäude":"komşu bina", "stürzte":"çöktü (einstürzen)", "komplett":"tamamen", "büros":"ofisler", "schule":"okul", "starben":"öldüler", "meisten":"çoğu", "kenianer":"kenyalılar", "tausende":"binlerce", "glassplitter":"cam kırıkları", "trümmer":"enkaz", "verletzt":"yaralı", "plante":"planladı", "erste":"ilk", "mal":"kez", "gruppe":"grup", "al-qaida":"el-kaide", "hörten":"duydular", "zeigte":"gösterdi", "terrorismus":"terörizm", "globales":"küresel", "problem":"problem" },
    questions: [ {q:"Griffen die Terroristen zwei Botschaften gleichzeitig an?", a_de:"Ja", a_tr:"Evet"}, {q:"Nutzen sie Lastwagen für die Bomben?", a_de:"Ja", a_tr:"Evet"}, {q:"Stürzte in Nairobi ein Gebäude ein?", a_de:"Ja", a_tr:"Evet"}, {q:"War in dem Gebäude auch eine Schule?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben nur Amerikaner?", a_de:"Nein", a_tr:"Hayır"}, {q:"Plante Osama bin Laden den Anschlag?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist Terrorismus ein globales Problem?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["16_Norwegen.mp3"] = [{
    text: "16. Die Anschläge in Norwegen. Die Anschläge in Norwegen ereigneten sich 2011. Ein Mann namens Anders Behring Breivik handelte allein. Er hatte extreme politische Ansichten. Zuerst zündete er eine Autobombe vor Regierungsgebäuden in Oslo. Acht Menschen starben. Dann fuhr er zur kleinen Insel Utøya. Dort fand ein Sommercamp für Jugendliche statt. Er verkleidete sich als Polizist. Er rief die jungen Leute zu sich und begann zu schießen. Er tötete 69 Menschen auf der Insel. Insgesamt starben 77 Menschen. Es war ein riesiger Schock, weil Norwegen sonst sehr sicher und friedlich ist. Der Mann wurde verhaftet und ins Gefängnis gesteckt. Die Norweger hielten zusammen und zeigten Liebe und Unterstützung für die Opfer.",
    dict: { "norwegen":"norveç", "ereigneten":"meydana geldi", "namens":"adında", "handelte":"hareket etti", "allein":"yalnız", "extreme":"aşırı", "politische":"siyasi", "ansichten":"görüşler", "zuerst":"önce", "zündete":"ateşledi", "autobombe":"bombalı araç", "regierungsgebäuden":"hükümet binaları", "oslo":"oslo", "acht":"sekiz", "starben":"öldüler", "fuhr":"gitti", "insel":"ada", "sommercamp":"yaz kampı", "jugendliche":"gençler", "stattfand":"gerçekleşti", "verkleidete":"kılık değiştirdi", "polizist":"polis", "rief":"çağırdı", "begann":"başladı", "schießen":"ateş etmek", "tötete":"öldürdü", "insgesamt":"toplamda", "riesiger":"devasa", "schock":"şok", "sonst":"normalde/aksi takdirde", "sicher":"güvenli", "friedlich":"huzurlu", "verhaftet":"tutuklandı", "gefängnis":"hapishane", "norweger":"norveçliler", "hielten":"tuttular (zusammenhalten: birlik olmak)", "liebe":"sevgi", "unterstützung":"destek", "opfer":"kurbanlar" },
    questions: [ {q:"Handelte der Täter in Norwegen allein?", a_de:"Ja", a_tr:"Evet"}, {q:"Zündete er zuerst eine Bombe in Oslo?", a_de:"Ja", a_tr:"Evet"}, {q:"Fand auf der Insel ein Fußballspiel statt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verkleidete er sich als Polizist?", a_de:"Ja", a_tr:"Evet"}, {q:"Tötete er 69 Menschen auf der Insel?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist Norwegen normalerweise ein friedliches Land?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde der Mann verhaftet?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["17_OklahomaCity.mp3"] = [{
    text: "17. Der Bombenanschlag von Oklahoma City. Der Bombenanschlag von Oklahoma City geschah 1995 in den USA. Timothy McVeigh war wütend auf die Regierung. Er mietete einen Lkw und füllte ihn mit Sprengstoff. Er parkte ihn vor einem großen Regierungsgebäude. Die Bombe explodierte und zerstörte die Vorderseite des Gebäudes. Es war eine riesige Explosion. 168 Menschen starben. Traurigerweise gab es im Gebäude eine Kindertagesstätte. Neunzehn kleine Kinder kamen ums Leben. Mehr als 600 Menschen wurden verletzt. McVeigh wurde kurz danach von einem Polizisten gefasst. Er wurde verurteilt und hingerichtet. Vor 9/11 war dies der schlimmste Terroranschlag in Amerika. Er zeigte, dass Terror auch aus dem eigenen Land kommen kann.",
    dict: { "bombenanschlag":"bombalı saldırı", "usa":"abd", "wütend":"kızgın", "regierung":"hükümet", "mietete":"kiraladı", "lkw":"kamyon", "füllte":"doldurdu", "sprengstoff":"patlayıcı", "parkte":"park etti", "regierungsgebäude":"hükümet binası", "explodierte":"patladı", "zerstörte":"yok etti/yıktı", "vorderseite":"ön taraf", "riesige":"devasa", "explosion":"patlama", "starben":"öldüler", "traurigerweise":"maalesef/üzücü bir şekilde", "kindertagesstätte":"kreş", "neunzehn":"on dokuz", "kleine":"küçük", "kinder":"çocuklar", "leben":"yaşam (ums Leben kommen: can vermek)", "verletzt":"yaralı", "kurz":"kısa", "danach":"sonra", "gefasst":"yakalandı", "verurteilt":"mahkum edildi", "hingerichtet":"idam edildi", "schlimmste":"en kötü", "kann":"olabilir" },
    questions: [ {q:"War Timothy McVeigh wütend auf die Regierung?", a_de:"Ja", a_tr:"Evet"}, {q:"Füllte er einen Lkw mit Sprengstoff?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde das ganze Gebäude zerstört?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben im Gebäude auch kleine Kinder?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben insgesamt 168 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde McVeigh niemals gefasst?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kam der Terror aus dem eigenen Land?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["18_Paris2015.mp3"] = [{
    text: "18. Die Anschläge in Paris. Die Anschläge in Paris ereigneten sich im November 2015 in Frankreich. Es war Freitagabend. Terroristen griffen gleichzeitig viele Orte in der Stadt an. Einige sprengten sich vor einem Fußballstadion in die Luft. Andere schossen in Restaurants und Cafés. Der schlimmste Anschlag war im Konzertsaal Bataclan. Eine Rockband spielte. Die Terroristen drangen ein und schossen in die Menge. Sie nahmen Geiseln. Die Polizei musste eindringen, um sie zu stoppen. In einer Nacht starben 130 Menschen, die meisten im Bataclan. Die Gruppe ISIS bekannte sich dazu. Frankreich war geschockt. Die Regierung schloss die Grenzen und rief den Notstand aus. Weltweit stellten Menschen die französische Flagge auf ihre Profile, um Solidarität zu zeigen.",
    dict: { "paris":"paris", "ereigneten":"meydana geldi", "frankreich":"fransa", "freitagabend":"cuma akşamı", "griffen":"saldırdılar", "viele":"birçok", "orte":"yerler", "stadt":"şehir", "sprengten":"patlattılar (in die Luft sprengen: havaya uçurmak)", "fußballstadion":"futbol stadyumu", "schossen":"ateş ettiler", "restaurants":"restoranlar", "cafés":"kafeler", "schlimmste":"en kötü", "konzertsaal":"konser salonu", "bataclan":"bataclan", "rockband":"rock grubu", "spielte":"çalıyordu", "drangen":"girdiler (eindringen)", "menge":"kalabalık", "geiseln":"rehineler", "polizei":"polis", "stoppen":"durdurmak", "nacht":"gece", "starben":"öldüler", "isis":"işid", "bekannte":"üstlendi (bekennen)", "geschockt":"şoke olmuş", "schloss":"kapattı", "grenzen":"sınırlar", "notstand":"olağanüstü hal", "weltweit":"dünya çapında", "französische":"fransız", "flagge":"bayrak", "profile":"profiller", "solidarität":"dayanışma", "zeigen":"göstermek" },
    questions: [ {q:"Fanden die Anschläge an einem Freitagabend statt?", a_de:"Ja", a_tr:"Evet"}, {q:"Griffen die Terroristen nur einen Ort an?", a_de:"Nein", a_tr:"Hayır"}, {q:"War der Bataclan ein Konzertsaal?", a_de:"Ja", a_tr:"Evet"}, {q:"Nahmen die Terroristen im Bataclan Geiseln?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben in dieser Nacht 130 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Rief die Regierung den Notstand aus?", a_de:"Ja", a_tr:"Evet"}, {q:"Zeigten Menschen weltweit Solidarität?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["19_Peshawar.mp3"] = [{
    text: "19. Das Massaker an der Schule in Peshawar. Das Massaker an der Schule in Peshawar geschah 2014 in Pakistan. Es war ein entsetzlicher Tag. Sieben Bewaffnete stürmten eine von der Armee betriebene Schule für Kinder. Die Angreifer schossen auf alle. Sie stellten keine Forderungen – sie wollten nur töten. Lehrer versuchten, die Schüler zu schützen. Der Angriff dauerte Stunden. Soldaten kamen und töteten die Angreifer. Doch 149 Menschen waren schon tot, die meisten Kinder. Es war sehr grausam. Das ganze Land weinte um die Kinder. Danach kämpfte Pakistan härter gegen Terroristen. Neue Gesetze wurden erlassen. Es gilt als der traurigste Tag in der Geschichte Pakistans.",
    dict: { "massaker":"katliam", "peshawar":"peşaver", "geschah":"oldu", "pakistan":"pakistan", "entsetzlicher":"dehşet verici", "sieben":"yedi", "bewaffnete":"silahlı", "stürmten":"bastılar", "armee":"ordu", "betriebene":"işletilen", "schule":"okul", "angreifer":"saldırganlar", "schossen":"ateş ettiler", "keine":"hiç/yok", "forderungen":"talepler", "töten":"öldürmek", "lehrer":"öğretmenler", "versuchten":"denediler", "schüler":"öğrenciler", "schützen":"korumak", "dauerte":"sürdü", "stunden":"saatler", "soldaten":"askerler", "tot":"ölü", "grausam":"zalim", "weinte":"ağladı", "kämpfte":"savaştı", "härter":"daha sert", "gesetze":"yasalar", "erlassen":"çıkarıldı", "traurigste":"en üzücü", "geschichte":"tarih" },
    questions: [ {q:"War die Schule in Peshawar für Kinder?", a_de:"Ja", a_tr:"Evet"}, {q:"Stellten die Angreifer viele Forderungen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Versuchten Lehrer, die Schüler zu schützen?", a_de:"Ja", a_tr:"Evet"}, {q:"Dauerte der Angriff nur zehn Minuten?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starben 149 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Waren die meisten Toten Kinder?", a_de:"Ja", a_tr:"Evet"}, {q:"Gilt es als der traurigste Tag in Pakistan?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["20_TokioSarin.mp3"] = [{
    text: "20. Der Sarin-Anschlag in der Tokioter U-Bahn. Der Sarin-Anschlag in der Tokioter U-Bahn geschah 1995 in Japan. Eine Sekte führte ihn durch. Sie wollte einen Krieg auslösen. Fünf Mitglieder stiegen morgens in U-Bahnen ein. Es war Stoßzeit, die Züge waren voll. Sie trugen Beutel mit dem Gift Sarin. Sie stachen Löcher hinein und verließen die Züge. Das Gift wurde zu Gas. Es machte Menschen sehr krank. Sie konnten nicht atmen oder sehen. Das Gas breitete sich in den Stationen aus. 13 Menschen starben, Tausende wurden krank. Es war sehr beängstigend, weil man das Gas nicht sah. Es war das erste Mal, dass Terroristen chemische Waffen in einer Stadt einsetzten. Japan verhaftete den Sektenführer und bestrafte ihn.",
    dict: { "tokioter":"tokyo", "u-bahn":"metro", "japan":"japonya", "sekte":"tarikat", "führte":"gerçekleştirdi (durchführen)", "krieg":"savaş", "auslösen":"başlatmak/tetiklemek", "fünf":"beş", "mitglieder":"üyeler", "stiegen":"bindiler", "morgens":"sabahları", "stoßzeit":"yoğun saat", "züge":"trenler", "voll":"dolu", "trugen":"taşıdılar", "beutel":"torbalar", "gift":"zehir", "sarin":"sarin", "stachen":"delik açtılar", "löcher":"delikler", "verließen":"terk ettiler", "gas":"gaz", "krank":"hasta", "atmen":"nefes almak", "sehen":"görmek", "breitete":"yayıldı (ausbreiten)", "stationen":"istasyonlar", "starben":"öldüler", "beängstigend":"korkutucu", "erste":"ilk", "mal":"kez", "chemische":"kimyasal", "waffen":"silahlar", "einsetzten":"kullandılar", "verhaftete":"tutukladı", "sektenführer":"tarikat lideri", "bestrafte":"cezalandırdı" },
    questions: [ {q:"Geschah der Anschlag in der U-Bahn von Tokio?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte die Sekte einen Krieg auslösen?", a_de:"Ja", a_tr:"Evet"}, {q:"War die U-Bahn fast leer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Nutzen die Täter das Gift Sarin?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde das Gift zu Gas?", a_de:"Ja", a_tr:"Evet"}, {q:"Sah man das Gas sehr deutlich?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurden chemische Waffen eingesetzt?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["21_Westgate.mp3"] = [{
    text: "21. Die Geiselnahme im Westgate-Einkaufszentrum. Die Geiselnahme im Westgate-Einkaufszentrum ereignete sich 2013 in Kenia. Das Westgate war ein schönes Einkaufszentrum für Reiche und Ausländer. Vier bewaffnete Männer der Gruppe Al-Shabaab drangen ein. Sie warfen Granaten und schossen auf Käufer. Sie blieben vier Tage im Gebäude. Polizei und Armee umstellten es. Es war schwer, die Männer zu fassen, weil das Zentrum groß war. Es brach Feuer aus, Teile des Gebäudes stürzten ein. Am Ende starben 67 Menschen. Viele weitere wurden verletzt. Die Terroristen sagten, sie griffen an, weil Kenia Soldaten nach Somalia geschickt hatte. Es machte die Menschen in Kenia lange Zeit Angst vor öffentlichen Orten.",
    dict: { "geiselnahme":"rehin alma", "westgate":"westgate", "einkaufszentrum":"alışveriş merkezi", "ereignete":"meydana geldi", "kenia":"kenya", "schönes":"güzel", "reiche":"zenginler", "ausländer":"yabancılar", "vier":"dört", "bewaffnete":"silahlı", "männer":"adamlar", "al-shabaab":"eş-şebab", "drangen":"girdiler (eindringen)", "warfen":"attılar", "granaten":"el bombaları", "schossen":"ateş ettiler", "käufer":"müşteriler", "blieben":"kaldılar", "tage":"günler", "gebäude":"bina", "polizei":"polis", "armee":"ordu", "umstellten":"kuşattılar", "schwer":"zor", "fassen":"yakalamak", "brach":"çıktı (ausbrechen)", "feuer":"yangın", "teile":"parçalar", "stürzten":"çöktü (einstürzen)", "ende":"son", "starben":"öldüler", "weitere":"diğer/başka", "verletzt":"yaralı", "griffen":"saldırdılar", "soldaten":"askerler", "somalia":"somali", "geschickt":"gönderilmiş", "lange":"uzun", "zeit":"süre", "angst":"korku", "öffentlichen":"kamusal", "orten":"yerler" },
    questions: [ {q:"War das Westgate ein Einkaufszentrum?", a_de:"Ja", a_tr:"Evet"}, {q:"Drangen vier bewaffnete Männer ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Blieben die Männer nur eine Stunde im Gebäude?", a_de:"Nein", a_tr:"Hayır"}, {q:"Brach im Zentrum ein Feuer aus?", a_de:"Ja", a_tr:"Evet"}, {q:"Starben insgesamt 67 Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Griffen die Terroristen wegen Somalias an?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatten die Menschen danach Angst vor öffentlichen Orten?", a_de:"Ja", a_tr:"Evet"} ]
}];
